In [ ]:
import numpy as np
import matplotlib.pyplot as plt

Notation:

n : number of datapoints

d : number of features in each datapoint

###*y = w'X + ϵ*

dim(y) -> 1*n,

dim(w) -> 1*d, 

dim(X) -> d*n

MLE estimate w/o regularization : 
**w* = (XX')<sup>-1</sup>(y'X)**

MLE estimate with regularization : 
**w* = (XX'+λI)<sup>-1</sup>(y'X)**



## Case1: n < d   ( number of datapoints less than the number of features )

In [ ]:
n = 5
d = 10

X = np.random.randn(d,n)
y = np.random.randn(1,n)

# The matrix has X has rank <= min(d,n) = 5
# rank(X*X.T) <= min(rank(X), rank(X.T)) <= 5 ( so it is a 10*10 matrix with rank less than equal to 5 so it is definitely singular )

Without regularization

In [ ]:
# The inverse is ill conditioned and not exactly singular bcoz of precision errors but nevertheless most elements in the inverse are blown up to 10^15
np.linalg.inv(np.matmul(X,X.T))

array([[-4.97369030e+14,  1.70480716e+14,  7.74366738e+14,
        -8.17256666e+14, -1.36546106e+15, -2.50671306e+14,
        -2.42837365e+15,  9.11346939e+14, -5.84327741e+14,
         1.37902470e+14],
       [ 3.08731973e+14, -1.35809540e+15, -1.27915704e+14,
        -1.49921490e+15, -3.40017131e+15,  6.43788768e+14,
        -1.52234773e+15,  3.90529009e+14, -4.12696822e+14,
        -2.00089803e+15],
       [ 2.85654623e+14, -2.45866543e+14,  3.28499320e+13,
         3.63397186e+14,  2.60790660e+15, -9.27306233e+14,
         9.04251084e+14, -3.72136898e+14, -4.90119094e+13,
         3.42799544e+14],
       [ 6.98832168e+13, -9.74227191e+14,  4.94997741e+14,
        -1.85148788e+15, -4.98780846e+15,  2.88082688e+14,
        -3.87102318e+15,  1.07080979e+15, -9.70988537e+14,
        -1.42971586e+15],
       [ 2.31806042e+15,  1.00011843e+15, -5.10432768e+14,
         3.97026532e+15,  2.65426830e+15, -6.03694222e+14,
         3.16874547e+15, -2.41492816e+15,  7.44024970e+12,
         3.

With regularization

In [ ]:
# Adding a small noise to the diagonal elements makes the inverse well-conditioned
LAMBDA = 0.01
np.linalg.inv(np.matmul(X,X.T)+LAMBDA*np.eye(d))

array([[ 47.40213205, -28.61229672,   0.61790597,  18.21773252,
         -9.10312949,  -9.00836683,   4.53557587, -25.72555954,
        -20.66330646,   5.97598853],
       [-28.61229672,  45.46292581,  -5.74130203,  15.18579522,
         -4.15076839,   3.43004877,  -1.8045226 ,  10.83216529,
         19.12912148,  29.28937855],
       [  0.61790597,  -5.74130203,  45.86486459,  -7.17217233,
         15.41164926,  28.30137022, -15.98180149,   9.02156849,
        -27.93731463,  15.42602639],
       [ 18.21773252,  15.18579522,  -7.17217233,  35.4836665 ,
         -4.28719265,  -2.69714983,  14.16684932, -18.25345796,
          1.29888654,  33.11077881],
       [ -9.10312949,  -4.15076839,  15.41164926,  -4.28719265,
         88.10111321, -17.06556962,  18.59107963,   2.77421863,
         -3.55320353,   5.49857889],
       [ -9.00836683,   3.43004877,  28.30137022,  -2.69714983,
        -17.06556962,  72.93782182,  26.88725321,   2.97267039,
         -6.10031957,  -1.83208007],
       [  

## Case2: n >= d   ( number of datapoints greater than the number of features )

In [ ]:
n = 20
d = 10

X = np.random.randn(d,n)
y = np.random.randn(1,n)

# Now the matrix wouldn't be singular with very high probability bcoz y would lie in the column space of 20 columns in R^10 with very high probability
# But still the issue of ill conditioning can arise with some finite probability when the columns lie close to a plane in which y doesn't fall

Without regularization

In [ ]:
# The inverse maybe well conditioned or ill conditioned
np.linalg.inv(np.matmul(X,X.T))

array([[ 1.20830649e-01,  1.38508089e-02, -3.55186376e-02,
         7.97663626e-02, -1.04650660e-02,  2.02064692e-02,
        -1.20066814e-02, -7.82705329e-02,  6.01107059e-02,
         2.24026077e-02],
       [ 1.38508089e-02,  1.71667325e-01, -6.49437905e-02,
         6.20296009e-02, -2.16801297e-02, -6.75630606e-02,
         1.53167021e-02, -3.55965385e-02, -5.69946767e-02,
         5.53941756e-03],
       [-3.55186376e-02, -6.49437905e-02,  1.12000563e-01,
        -5.18300798e-02, -2.69993694e-02,  1.53664358e-02,
        -2.25683728e-02,  6.32634332e-02, -5.13934570e-05,
        -3.82471005e-03],
       [ 7.97663626e-02,  6.20296009e-02, -5.18300798e-02,
         2.75305190e-01,  4.37857740e-02, -1.80930987e-02,
         4.29588215e-03, -2.13747347e-01,  3.02091739e-02,
         3.18745936e-02],
       [-1.04650660e-02, -2.16801297e-02, -2.69993694e-02,
         4.37857740e-02,  9.39651285e-02,  1.96778097e-02,
         1.50034929e-02, -4.96251647e-02,  1.59332285e-02,
         1.

With regularization

In [ ]:
# Adding a small noise to the diagonal elements makes the inverse well-conditioned even if it was ill conditioned originally
LAMBDA = 0.01
np.linalg.inv(np.matmul(X,X.T)+LAMBDA*np.eye(d))

array([[ 1.20499012e-01,  1.37567474e-02, -3.53448512e-02,
         7.92427676e-02, -1.05363036e-02,  2.01033123e-02,
        -1.19738293e-02, -7.76892602e-02,  5.98440135e-02,
         2.22538310e-02],
       [ 1.37567474e-02,  1.71193511e-01, -6.46928438e-02,
         6.16457278e-02, -2.16637591e-02, -6.73222775e-02,
         1.52695801e-02, -3.53278233e-02, -5.67976982e-02,
         5.52112451e-03],
       [-3.53448512e-02, -6.46928438e-02,  1.11739595e-01,
        -5.14112566e-02, -2.69071972e-02,  1.53169127e-02,
        -2.25315611e-02,  6.28440137e-02, -1.35870778e-05,
        -3.75339164e-03],
       [ 7.92427676e-02,  6.16457278e-02, -5.14112566e-02,
         2.73927400e-01,  4.35222950e-02, -1.81233027e-02,
         4.31253750e-03, -2.12369336e-01,  2.99116396e-02,
         3.15869702e-02],
       [-1.05363036e-02, -2.16637591e-02, -2.69071972e-02,
         4.35222950e-02,  9.38107491e-02,  1.96009547e-02,
         1.49906671e-02, -4.93170286e-02,  1.58210581e-02,
         1.